### PR TITLE
Report page has been updated to have textboxes that are linked to the firebase, fixes issue #13 

### LINKED ISSUE #9: No report button
### Issue: Add a Report Button for Unauthorized Parking
**Description:**
Currently, there is no way for users to report a vehicle that has taken their reserved spot. To improve the system, we need to add a "Report" button that allows users to flag unauthorized parking in their reserved space.

**Steps to Reproduce:**

- A user reserves a parking spot.
- Upon arrival, they find that another vehicle has taken their reserved space.
- There is currently no option to report this issue within the app.

**Expected Behavior:**

- A "Report" button should be available on the reservation screen.
- When tapped, it should open a form where users can provide details (e.g., license plate number, vehicle description).
- The report should be logged in the system for further action.

**Proposed Solution:**

- Add a "Report Violation" button to the reservation screen.
- Create a simple form to collect relevant details (license plate, vehicle make/model, optional comments).
- Ensure reports are stored in the database for review.

**Priority:** High
**Type:**  New Feature

### LINKED ISSUE #13: We need to be able to input text into the fields we are asking for.
As of now, we have the main contents:

```
      {/* Main Content */}
      <View style={styles.content}>
        <Text style={styles.text}>Report</Text>
         {/* Vehicle Number Input */}
         <Text style={styles.label}>License Plate Number:</Text>
         {/* Color Input */}
         <Text style={styles.label}>Color:</Text>
         {/* Make Input */}
         <Text style={styles.label}>Make/Model:</Text>
         {/* Comments */}
         <Text style={styles.label}>Comments:</Text>
      </View>
    </View>
```
but we cannot actually take in any input. 

we need to connect the firebase storage to the page and create input textboxes so that the user can actually make a report and input information that is asked for.

### PR DESCRIPTION
**Pull request by Ultramd**
A fix for issue #13 

### This pull request focuses on improving the ReportScreen.js file by:

1. Adding text input fields for users to enter vehicle violation details.
2. Implementing Firebase Firestore integration to store report data.
3. Improving the UI with better structuring and spacing for input fields and the submit button.
4. Ensuring that userId and timestamp are automatically assigned, reducing user input requirements.

### Changes & Code Quality Review
 _**Enhanced Functionality**:_

- The addition of Firestore integration allows users to submit reports and store them persistently.

- Automatically assigning userId and timestamp improves efficiency and security.

_**Improved User Experience:**_

- Added structured input fields for license plate number, vehicle color, make/model, and comments.

- Proper UI labels for better readability.

_**Code Readability & Formatting:**_

- Well-structured code with appropriate comments for each section.

- Consistent indentation and spacing.

### Type of Change

- [ ]  Bugfix
- [x]  New Feature
- [ ]  Documentation Update
- [ ]  Other (please describe):

### Potential Improvements / Issues to Address

-  Button Placement Optimization
-  Page Customization
- The commits for firebase was simply because github needed me to commit but firebase was already implemented

### CODE REVIEW

File: screens/ReportScreen.js [hunk 1]
```diff
@@ -1,30 +1,48 @@
...
+      await addDoc(collection(db, "reports"), {
+        licensePlate,
+        color,
+        makeModel,
+        comments,
+        userId: user.uid, // Automatically assign the logged-in user’s ID
+        timestamp: serverTimestamp(), // Automatically generate a timestamp
+      });
+
+      Alert.alert("Success", "Report submitted successfully!");
```
Comment (josephdib3160) [inline screens/ReportScreen.js:34]: a confirmation button could be added here

**Review by josephdib3160 — APPROVED** [review]
### What is good:
 - Text boxes work for the report button
 - Report information saves to the database online

### What could be improved:
 - Confirmation prompts could be added
 - Information as to what happens after a report
 - Small spacing adjustments

 ## Pull Request is accepted
